name: Push Docker Image to DockerHub

on:
  push:
    branches:
      - main # or master, or whichever branch you want

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            thejoud1997/${{ github.event.repository.name }}:latest
            thejoud1997/${{ github.event.repository.name }}:${{ github.sha }}

      - name: Logout from DockerHub
        run: docker logout
